name: GitHub actions kustomize argocd manifests
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used sync ArgoCD apps
branding:
  icon: feather
  color: gray-dark

inputs:
  appid:
    description: 'The App ID'
    required: true
  tokenargo:
    description: 'The ArgoCD token to authenticate'
    required: true
  env:
    description: 'The app env (develop|homolog|prod)'
    required: true
  argourl:
    description: 'The ArgoCD URL'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appid }}
    - ${{ inputs.tokenargo }}
    - ${{ inputs.env }}
    - ${{ inputs.argourl }}